#!/usr/bin/env node
/**
 * T5: zero-dependency design-token generator.
 *
 * Reads design/tokens.json (canonical design truth) and emits
 * frontend/src/tokens.css. Run from frontend/: `npm run tokens`.
 *
 * Modes:
 *   node scripts/gen-tokens.mjs            write tokens.css
 *   node scripts/gen-tokens.mjs --check    regenerate in memory, diff
 *                                          against the committed file,
 *                                          exit 1 on drift (CI gate)
 *
 * Paths are resolved relative to this script so the check works from
 * any working directory. Only Node builtins are used.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(scriptDir, "..");
const repoRoot = resolve(frontendDir, "..");
const tokensPath = join(repoRoot, "design", "tokens.json");
const outPath = join(frontendDir, "src", "tokens.css");

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

/** `color."surface.canvas"` -> `--pw-color-surface-canvas` */
function cssName(prefix, name) {
  return `--pw-${prefix}-${name
    .replace(/[._]/g, "-")
    .toLowerCase()}`;
}

function sectionEntries(obj) {
  return Object.entries(obj).filter(([k]) => !k.startsWith("_"));
}

function emit(root) {
  const lines = [];
  const warn = [];

  lines.push("/* generated */");
  lines.push("/* Design tokens generated by frontend/scripts/gen-tokens.mjs");
  lines.push("   from design/tokens.json — canonical design truth.");
  lines.push("   Do not edit this file by hand; run `npm run tokens`. */");
  lines.push("");

  // ── Colors (dark default) ──────────────────────────────────
  const dark = sectionEntries(root.color ?? {}).filter(
    ([k]) => !k.startsWith("light.")
  );
  const light = sectionEntries(root.color ?? {}).filter(([k]) =>
    k.startsWith("light.")
  );
  lines.push(":root {");
  for (const [name, value] of dark) {
    lines.push(`  ${cssName("color", name)}: ${value};`);
  }
  lines.push("}");
  lines.push("");

  // Light theme: explicit attribute + OS preference when no explicit
  // theme attribute is present (spec §4).
  const lightPairs = light.map(([k, v]) => [
    k.replace(/^light\./, ""),
    v,
  ]);
  // Explicit theme attribute wins; otherwise the OS preference applies
  // when no explicit theme is set (spec §4).
  for (const [selector] of [
    ['[data-pw-theme="light"]'],
    ["@media (prefers-color-scheme: light) { :root:not([data-pw-theme])"],
  ]) {
    lines.push(`${selector} {`);
    for (const [name, value] of lightPairs) {
      lines.push(`  ${cssName("color", name)}: ${value};`);
    }
    if (selector.startsWith("@media")) {
      lines.push("} }");
    } else {
      lines.push("}");
    }
  }
  lines.push("");

  // ── Spacing ─────────────────────────────────────────────────
  const spacing = sectionEntries(root.spacing ?? {});
  if (spacing.length) {
    lines.push(":root {");
    for (const [name, value] of spacing) {
      lines.push(`  ${cssName("spacing", name.replace(/^spacing\./, ""))}: ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  // ── Target sizes (44px floor) ───────────────────────────────
  const targets = sectionEntries(root.targets ?? {});
  if (targets.length) {
    lines.push(":root {");
    for (const [name, value] of targets) {
      lines.push(`  ${cssName("target", name.replace(/^targets\./, ""))}: ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  // ── Typography ──────────────────────────────────────────────
  const typography = sectionEntries(root.typography ?? {});
  if (typography.length) {
    lines.push(":root {");
    for (const [name, value] of typography) {
      lines.push(`  ${cssName("typography", name)}: ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  // ── Focus ───────────────────────────────────────────────────
  const focus = sectionEntries(root.focus ?? {});
  for (const [name, value] of focus) {
    const suffix = name.replace(/^focus\.ring/, "");
    const varName = suffix
      ? `--pw-focus-ring${suffix.replace(/^_/, "-").replace(/_/g, "-").toLowerCase()}`
      : "--pw-focus-ring";
    lines.push(`:root { ${varName}: ${value}; }`);
  }
  lines.push("");

  // ── Motion variables (spec §3): off/reduced 0ms·0, subtle 200ms·1.
  // Runtime tiers live in the server-rendered prefs style block keyed
  // by data-pw-motion; these are the static defaults (reduced).
  const motionDefault = (root.motion?.["motion.default"] ?? "reduced").trim();
  const tier = motionDefault === "subtle"
    ? { duration: "200ms", ambient: "1" }
    : { duration: "0ms", ambient: "0" };
  lines.push(
    `:root { --pw-motion-duration: ${tier.duration}; --pw-motion-ambient: ${tier.ambient}; }`
  );
  lines.push("");

  // ── Unconditional OS override (A11y contract §6.2) ─────────
  lines.push("@media (prefers-reduced-motion: reduce) {");
  lines.push("  *,");
  lines.push("  *::before,");
  lines.push("  *::after {");
  lines.push("    animation: none !important;");
  lines.push("    transition: none !important;");
  lines.push("  }");
  lines.push("  :root {");
  lines.push("    --pw-motion-duration: 0ms;");
  lines.push("    --pw-motion-ambient: 0;");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  if (warn.length) {
    for (const w of warn) process.stderr.write(`gen-tokens: ${w}\n`);
  }
  return lines.join("\n");
}

const css = `${emit(tokens)}\n`;

if (process.argv.includes("--check")) {
  let committed;
  try {
    committed = readFileSync(outPath, "utf8");
  } catch {
    process.stderr.write(
      "tokens:check: frontend/src/tokens.css is missing. Run `npm run tokens` and commit it.\n"
    );
    process.exit(1);
  }
  if (committed !== css) {
    process.stderr.write(
      "tokens:check: frontend/src/tokens.css is out of date with design/tokens.json.\n" +
        "Run `npm run tokens` and commit the regenerated file.\n"
    );
    process.exit(1);
  }
  process.stdout.write("tokens:check: tokens.css matches design/tokens.json\n");
} else {
  writeFileSync(outPath, css);
  process.stdout.write(
    `gen-tokens: wrote ${join("src", "tokens.css")} (${css.length} bytes)\n`
  );
}